In [357]:
import numpy as np
import pandas as pd

**Passo 01 )**
- Definir a matriz de entrada _X_ com dimensões $(n, d)$ e o parâmetro _k_, validando se o número de clusters é menor ou igual ao número total de amostras disponíveis.

**Passo 02 )**
- Inicializar os _centroides_ através da seleção aleatória de _k_ amostras distintas extraídas do conjunto de dados original.

**Passo 03 )**
- Calcular a matriz de distâncias entre cada ponto e cada centroide utilizando o quadrado da norma euclidiana $\|x^{(i)} - \mu_j\|^2$ por meio de operações vetorizadas.

**Passo 04 )**
- Atribuir cada amostra ao índice do centroide que resultou na menor distância quadrada calculada no passo anterior.

**Passo 05 )**
- Atualizar a posição de cada centroide calculando a _média aritmética_ de todos os vetores de características pertencentes ao respectivo cluster.

**Passo 06 )**
- Identificar a existência de clusters vazios e implementar uma rotina de reinicialização para qualquer centroide que não possua pontos atribuídos.

**Passo 07 )**
- Avaliar a convergência comparando a variação dos centroides entre iterações consecutivas em relação a uma tolerância _epsilon_ ou ao limite de iterações.

**Passo 08 )**
- Retornar os vetores de posição dos centroides finais e o array contendo os rótulos de identificação de cluster para cada amostra.

In [358]:
one_d_data = np.array([0,1,2,3,4,5,6,12,13,15,16,18,25,27,29,30])

In [359]:
def get_cent(X, k):
    list_cent = []
    for i in range(k):
        indice = np.random.choice(len(X), size=1, replace=False)[0]
        valor = X[indice]
        list_cent.append(valor)
        X = np.delete(X, indice)
    return np.array(list_cent)

list_cent = get_cent(one_d_data, 3)
print(list_cent)

[25 15 30]


In [360]:
def calc_dist(X, list_cent):
    labels = []
    for x in X:
        distancias = []
        for c in list_cent:
            d = np.sum((x - c)**2)
            distancias.append(d)
        
        labels.append(np.argmin(distancias))
    
    return np.column_stack((labels, X))

list_cent_gruped = calc_dist(one_d_data, list_cent=list_cent)
print(list_cent_gruped)

[[ 1  0]
 [ 1  1]
 [ 1  2]
 [ 1  3]
 [ 1  4]
 [ 1  5]
 [ 1  6]
 [ 1 12]
 [ 1 13]
 [ 1 15]
 [ 1 16]
 [ 1 18]
 [ 0 25]
 [ 0 27]
 [ 2 29]
 [ 2 30]]


In [361]:
def calc_cent_mean(C):
    df_c = pd.DataFrame({'Cluster' : C[:,0], 'Values' : C[:,1]})
    return df_c.groupby('Cluster').mean().to_numpy().flatten()

new_list_cent = calc_cent_mean(list_cent_gruped)
print(new_list_cent)
print(list_cent)

[26.          7.91666667 29.5       ]
[25 15 30]


In [362]:
def kmeans(X, k, iterations):
    list_cent = get_cent(X, k)
    
    for i in range(iterations):
        list_cent_grouped = calc_dist(X, list_cent)
        
        new_list_cent = calc_cent_mean(list_cent_grouped)
        
        list_cent = new_list_cent
        
    return list_cent_grouped, list_cent

Data, y = kmeans(one_d_data, 3, 10)

In [363]:
Data

array([[ 2,  0],
       [ 2,  1],
       [ 2,  2],
       [ 2,  3],
       [ 2,  4],
       [ 2,  5],
       [ 2,  6],
       [ 1, 12],
       [ 1, 13],
       [ 1, 15],
       [ 1, 16],
       [ 1, 18],
       [ 0, 25],
       [ 0, 27],
       [ 0, 29],
       [ 0, 30]])

In [364]:
y

array([27.75, 14.8 ,  3.  ])